version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - mvn package
      - docker build -t spring-test .
      - docker tag spring-test 643463487162.dkr.ecr.us-east-1.amazonaws.com/spring-test-aws
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 643463487162.dkr.ecr.us-east-1.amazonaws.com/spring-test-aws